[package]
name = "pio-core"
version = "0.3.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7", default-features = false }
paste = "1.0"
num_enum = { version = "0.7", default-features = false }
